lines = {
  km: [
    {
      name: "KM1",
      color: "green-line",
      icon: "mdi-maps-directions-train",
      type: "km",
      directions: [
        {name: "Warszawa Wschodnia → Pruszków"},
        {name: "Pruszków → Warszawa Wschodnia"},
      ]
    },
    {
      name: "KM2",
      color: "green-line",
      icon: "mdi-maps-directions-train",
      type: "km",
      directions: [
        {name: "Warszawa Zachodnia → Sulejówek Miłosna"},
        {name: "Sulejówek Miłosna → Warszawa Zachodnia"},
      ]
    },
    {
      name: "KM3",
      color: "green-line",
      icon: "mdi-maps-directions-train",
      type: "km",
      directions: [
        {name: "Warszawa Wschodnia → Płochocin"},
        {name: "Płochocin → Warszawa Wschodnia"},
      ]
    },
    {
      name: "KM6",
      color: "green-line",
      icon: "mdi-maps-directions-train",
      type: "km",
      directions: [
        {name: "Warszawa Zacisze Wilno → Warszawa Wileńska"},
        {name: "Warszawa Wileńska → Warszawa Zacisze Wilno"},
      ]
    },
    {
      name: "KM7",
      color: "green-line",
      icon: "mdi-maps-directions-train",
      type: "km",
      directions: [
        {name: "Warszawa Zachodnia → Śródborów"},
        {name: "Śródborów → Warszawa Zachodnia"},
      ]
    },
    {
      name: "KM8",
      color: "green-line",
      icon: "mdi-maps-directions-train",
      type: "km",
      directions: [
        {name: "Warszawa Wschodnia → Warszawa Śródmieście → Zalesie Górne"},
        {name: "Zalesie Górne → Warszawa Śródmieście → Warszawa Wschodnia"},
        {name: "Warszawa Wschodnia → Warszawa Centralna → Zalesie Górne"},
        {name: "Zalesie Górne → Warszawa Centralna → Warszawa Wschodnia"},
        
      ]
    },
    {
      name: "KM9",
      color: "green-line",
      icon: "mdi-maps-directions-train",
      type: "km",
      directions: [
        {name: "Warszawa Zachodnia → Legionowo Przystanek"},
        {name: "Legionowo Przystanek → Warszawa Zachodnia"},
        {name: "Legionowo Piaski → Warszawa Gdańska"},
        {name: "Warszawa Zachodnia → Warszawa Centralna → Legionowo Przystanek"},
        {name: "Warszawa Wschodnia → Warszawa Toruńska"}


      ]
    },{
      name: "KML",
      color: "green-line",
      icon: "mdi-maps-directions-train",
      type: "km",
      directions: [
        {name: "Warszawa Lotnisko Chopina → Legionowo Przystanek"},
        {name: "Legionowo Przystanek → Warszawa Lotnisko Chopina"},
      ]
    },
  ],
  skm:[
    {
      name: "S1",
      color: "orange-line",
      icon: "mdi-maps-directions-train",
      type: "skm",
      directions: [
        {name: "Pruszków → Otwock"},
        {name: "Otwock → Pruszków"},
      ]
    },
    {
      name: "S2",
      color: "orange-line",
      icon: "mdi-maps-directions-train",
      type: "skm",
      directions: [
        {name: "Warszawa Lotnisko Chopina → Sulejówek"},
        {name: "Sulejówek → Warszawa Lotnisko Chopina"},
      ]
    },
    {
      name: "S3",
      color: "orange-line",
      icon: "mdi-maps-directions-train",
      type: "skm",
      directions: [
        {name: "Warszawa Lotnisko Chopina → Wieliszew"},
        {name: "Wieliszew → Warszawa Lotnisko Chopina"},
      ]
    },
    {
      name: "S9",
      color: "orange-line",
      icon: "mdi-maps-directions-train",
      type: "skm",
      directions: [
        {name: "Warszawa Zachodnia → Legionowo Piaski"},
        {name: "Legionowo Piaski → Warszawa Zachodnia"},
      ]
    },
    
    
    
  ],
  wkd: [
    {
      name: "WKD",
      color: "purple-line",
      icon: "mdi-maps-directions-train",
      type: "wkd",
      directions: [
        {name: "Grodzisk Mazowiecki → Warszawa"},
        {name: "Warszawa → Grodzisk Mazowiecki"},
        {name: "Milanówek → Warszawa"},
        {name: "Warszawa → Milanówek"}
      ]
    },
  ],
  metro: [
    {
      name: "M1",
      color: "blue-line",
      icon: "mdi-maps-directions-subway",
      type: "metro",
      directions: [
        {name: "Młociny → Kabaty"},
        {name: "Kabaty → Młociny"}
      ]
    },
    {
      name: "M2",
      color: "red-line",
      icon: "mdi-maps-directions-subway",
      type: "metro",
      directions: [
        {name: "Rondo Daszyńskiego → Dworzec Wileński"},
        {name: "Dworzec Wileński → Rondo Daszyńskiego"}
      ]
    },
  ]
};

stations = {
  "Warszawa Lotnisko Chopina → Legionowo Przystanek":[
    {name: "Warszawa Lotnisko Chopina"},
    {name: "Warszawa Służewiec"},
    {name: "Warszawa Żwirki I Wigury"},
    {name: "Warszawa Rakowiec"},
    {name: "Warszawa Al.Jerozolimskie"},
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Centralna"},
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Toruńska"},
    {name: "Warszawa Płudy"},
    {name: "Legionowo"},
    {name: "Legionowo przystanek"}
  ],
  "Legionowo Przystanek → Warszawa Lotnisko Chopina":[
    {name: "Legionowo przystanek"},
    {name: "Legionowo"},
    {name: "Warszawa Płudy"},
    {name: "Warszawa Toruńska"},
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Centralna"},
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Al.Jerozolimskie"},
    {name: "Warszawa Rakowiec"},
    {name: "Warszawa Żwirki I Wigury"},
    {name: "Warszawa Służewiec"},
    {name: "Warszawa Lotnisko Chopina"}
  ],
  "Warszawa Zachodnia → Legionowo Przystanek":[
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Kasprzaka"},
    {name: "Warszawa Koło"},
    {name: "Warszawa Gdańska"},
    {name: "Warszawa ZOO"},
    {name: "Warszawa Praga"},
    {name: "Warszawa Toruńska"},
    {name: "Warszawa Żerań"},
    {name: "Warszawa Płudy"},
    {name: "Warszawa Choszczówka"},
    {name: "Legionowo"},
    {name: "Legionowo Przystanek"}
  ],
  "Legionowo Przystanek → Warszawa Zachodnia":[
    {name: "Legionowo Przystanek"},
    {name: "Legionowo"},
    {name: "Warszawa Choszczówka"},
    {name: "Warszawa Płudy"},
    {name: "Warszawa Żerań"},
    {name: "Warszawa Toruńska"},
    {name: "Warszawa Praga"},
    {name: "Warszawa ZOO"},
    {name: "Warszawa Gdańska"},
    {name: "Warszawa Koło"},
    {name: "Warszawa Kasprzaka"},
    {name: "Warszawa Zachodnia"}
  ], 
  "Legionowo Piaski → Warszawa Gdańska":[
    {name: "Legionowo Piaski"},
    {name: "Legionowo"},
    {name: "Warszawa Płudy"},
    {name: "Warszawa Toruńska"},
    {name: "Warszawa ZOO"},
    {name: "Warszawa Gdańska"}
  ],
  "Warszawa Zachodnia → Warszawa Centralna → Legionowo Przystanek":[
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Centralna"},
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Praga"},
    {name: "Warszawa Toruńska"},
    {name: "Warszawa Żerań"},
    {name: "Warszawa Płudy"},
    {name: "Warszawa Choszczówka"},
    {name: "Legionowo"},
    {name: "Legionowo Przystanek"}
  ],
  "Warszawa Wschodnia → Warszawa Toruńska":[
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa ZOO"},
    {name: "Warszawa Gdańska"}
  ],
  "Warszawa Wschodnia → Warszawa Centralna → Zalesie Górne":[
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Centralna"},
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Rakowiec"},
    {name: "Warszawa Żwirki I Wigury"},
    {name: "Warszawa Służewiec"},
    {name: "Nowa Iwiczna"},
    {name: "Piaseczno"},
    {name: "Zalesie Górne"}
  ],
  "Zalesie Górne → Warszawa Centralna → Warszawa Wschodnia":[
    {name: "Zalesie Górne"},
    {name: "Piaseczno"},
    {name: "Nowa Iwiczna"},
    {name: "Warszawa Służewiec"},
    {name: "Warszawa Żwirki I Wigury"},
    {name: "Warszawa Rakowiec"},
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Centralna"},
    {name: "Warszawa Wschodnia"}
  ],
  "Warszawa Wschodnia → Warszawa Śródmieście → Zalesie Górne":[
    {name: "Zalesie Górne"},
    {name: "Piaseczno"},
    {name: "Nowa Iwiczna"},
    {name: "Warszawa Jeziorki"},
    {name: "Warszawa Dawidy"},
    {name: "Warszawa Okęcie"},
    {name: "Warszawa Służewiec"},
    {name: "Warszawa Żwirki I Wigury"},
    {name: "Warszawa Rakowiec"},
    {name: "Warszawa Al.Jerozolimskie"},
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Ochota"},
    {name: "Warszawa Śródmieście"},
    {name: "Warszawa Powiśle"},
    {name: "Warszawa Stadion"},
    {name: "Warszawa Wschodnia"},
  ],
  "Zalesie Górne → Warszawa Śródmieście → Warszawa Wschodnia":[
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Stadion"},
    {name: "Warszawa Powiśle"},
    {name: "Warszawa Śródmieście"},
    {name: "Warszawa Ochota"},
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Al.Jerozolimskie"},
    {name: "Warszawa Rakowiec"},
    {name: "Warszawa Żwirki I Wigury"},
    {name: "Warszawa Służewiec"},
    {name: "Warszawa Okęcie"},
    {name: "Warszawa Dawidy"},
    {name: "Warszawa Jeziorki"},
    {name: "Nowa Iwiczna"},
    {name: "Piaseczno"},
    {name: "Zalesie Górne"},
  ],
  "Warszawa Zachodnia → Śródborów":[
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Ochota"},
    {name: "Warszawa Śródmieście"},
    {name: "Warszawa Powiśle"},
    {name: "Warszawa Stadion"},
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Olszynka Grochowska"},
    {name: "Warszawa Gocławek"},
    {name: "Warszawa Wawer"},
    {name: "Warszawa Anin"},
    {name: "Warszawa Międzylesie"},
    {name: "Warszawa Radość"},
    {name: "Warszawa Miedzeszyn"},
    {name: "Warszawa Falenica"},
    {name: "Michalin"},
    {name: "Józefów"},
    {name: "Świder"},
    {name: "Otwock"},
    {name: "Śródborów"},
  ],
  "Śródborów → Warszawa Zachodnia":[
    {name: "Śródborów"},
    {name: "Otwock"},
    {name: "Świder"},
    {name: "Józefów"},
    {name: "Michalin"},
    {name: "Warszawa Falenica"},
    {name: "Warszawa Miedzeszyn"},
    {name: "Warszawa Radość"},
    {name: "Warszawa Międzylesie"},
    {name: "Warszawa Anin"},
    {name: "Warszawa Wawer"},
    {name: "Warszawa Gocławek"},
    {name: "Warszawa Olszynka Grochowska"},
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Stadion"},
    {name: "Warszawa Powiśle"},
    {name: "Warszawa Śródmieście"},
    {name: "Warszawa Ochota"},
    {name: "Warszawa Zachodnia"}
  ],
  "Warszawa Zacisze Wilno → Warszawa Wileńska":[
    {name: "Warszawa Zacisze-Wilno"},
    {name: "Warszawa Wileńska"}
  ],
  "Warszawa Wileńska → Warszawa Zacisze Wilno":[
    {name: "Warszawa Wileńska"},
    {name: "Warszawa Zacisze-Wilno"}
  ],
  "Warszawa Wschodnia → Płochocin":[
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Stadion"},
    {name: "Warszawa Powiśle"},
    {name: "Warszawa Śródmieście"},
    {name: "Warszawa Ochota"},
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Włochy"},
    {name: "Warszawa Ursus Płn."},
    {name: "Warszawa Gołąbki"},
    {name: "Ożarów Maz."},
    {name: "Płochocin"},
  ],
  "Płochocin → Warszawa Wschodnia":[
    {name: "Płochocin"},
    {name: "Ożarów Maz."},
    {name: "Warszawa Gołąbki"},
    {name: "Warszawa Ursus Płn."},
    {name: "Warszawa Włochy"},
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Ochota"},
    {name: "Warszawa Śródmieście"},
    {name: "Warszawa Powiśle"},
    {name: "Warszawa Stadion"},
    {name: "Warszawa Wschodnia"}
  ],
  "Warszawa Zachodnia → Sulejówek Miłosna": [
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Ochota"},
    {name: "Warszawa Śródmieście"},
    {name: "Warszawa Powiśle"},
    {name: "Warszawa Stadion"},
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Rembertów"},
    {name: "Warszawa Wesoła"},
    {name: "Warszawa Wola Grzybowska"},
    {name: "Sulejówek"},
    {name: "Sulejówek Miłosna"}
  ],
  "Sulejówek Miłosna → Warszawa Zachodnia": [
    {name: "Sulejówek Miłosna"},
    {name: "Sulejówek"},
    {name: "Warszawa Wola Grzybowska"},
    {name: "Warszawa Wesoła"},
    {name: "Warszawa Rembertów"},
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Stadion"},
    {name: "Warszawa Powiśle"},
    {name: "Warszawa Śródmieście"},
    {name: "Warszawa Ochota"},
    {name: "Warszawa Zachodnia"}
  ],
  "Warszawa Wschodnia → Pruszków": [
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Stadion"},
    {name: "Warszawa Powiśle"},
    {name: "Warszawa Śródmieście"},
    {name: "Warszawa Ochota"},
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Włochy"},
    {name: "Warszawa Ursus"},
    {name: "Warszawa Ursus-Niedźwiadek"},
    {name: "Piastów"},
    {name: "Pruszków"},
  ],
  "Pruszków → Warszawa Wschodnia":[
    {name: "Pruszków"},
    {name: "Piastów"},
    {name: "Warszawa Ursus-Niedźwiadek"},
    {name: "Warszawa Ursus"},
    {name: "Warszawa Włochy"},
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Ochota"},
    {name: "Warszawa Śródmieście"},
    {name: "Warszawa Powiśle"},
    {name: "Warszawa Stadion"},
    {name: "Warszawa Wschodnia"},
  ],
  "Pruszków → Otwock": [
    {name: "Pruszków"},
    {name: "Piastów"},
    {name: "Warszawa Ursus-Niedźwiadek"},
    {name: "Warszawa Ursus"},
    {name: "Warszawa Włochy"},
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Ochota"},
    {name: "Warszawa Śródmieście"},
    {name: "Warszawa Powiśle"},
    {name: "Warszawa Stadion"},
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Olszynka Grochowska"},
    {name: "Warszawa Gocławek"},
    {name: "Warszawa Wawer"},
    {name: "Warszawa Anin"},
    {name: "Warszawa Międzylesie"},
    {name: "Warszawa Radość"},
    {name: "Warszawa Miedzeszyn"},
    {name: "Warszawa Falenica"},
    {name: "Michalin"},
    {name: "Józefów"},
    {name: "Świder"},
    {name: "Otwock"}
  ],

  "Otwock → Pruszków": [
    {name: "Otwock"},
    {name: "Świder"},
    {name: "Józefów"},
    {name: "Michalin"},
    {name: "Warszawa Falenica"},
    {name: "Warszawa Miedzeszyn"},
    {name: "Warszawa Radość"},
    {name: "Warszawa Międzylesie"},
    {name: "Warszawa Anin"},
    {name: "Warszawa Wawer"},
    {name: "Warszawa Gocławek"},
    {name: "Warszawa Olszynka Grochowska"},
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Stadion"},
    {name: "Warszawa Powiśle"},
    {name: "Warszawa Śródmieście"},
    {name: "Warszawa Ochota"},
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Włochy"},
    {name: "Warszawa Ursus"},
    {name: "Warszawa Ursus-Niedźwiadek"},
    {name: "Piastów"},
    {name: "Pruszków"},
  ],

  "Warszawa Lotnisko Chopina → Sulejówek": [
    {name: "Warszawa Lotnisko Chopina"},
    {name: "Warszawa Służewiec"},
    {name: "Warszawa Żwirki I Wigury"},
    {name: "Warszawa Rakowiec"},
    {name: "Warszawa Al.Jerozolimskie"},
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Ochota"},
    {name: "Warszawa Śródmieście"},
    {name: "Warszawa Powiśle"},
    {name: "Warszawa Stadion"},
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Rembertów"},
    {name: "Warszawa Wesoła"},
    {name: "Warszawa Wola Grzybowska"},
    {name: "Sulejówek"},
    {name: "Sulejówek Miłosna"}
  ],

  "Sulejówek → Warszawa Lotnisko Chopina": [
    {name: "Sulejówek Miłosna"},
    {name: "Sulejówek"},
    {name: "Warszawa Wola Grzybowska"},
    {name: "Warszawa Wesoła"},
    {name: "Warszawa Rembertów"},
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Stadion"},
    {name: "Warszawa Powiśle"},
    {name: "Warszawa Śródmieście"},
    {name: "Warszawa Ochota"},
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Al.Jerozolimskie"},
    {name: "Warszawa Rakowiec"},
    {name: "Warszawa Żwirki I Wigury"},
    {name: "Warszawa Służewiec"},
    {name: "Warszawa Lotnisko Chopina"}
  ],

  "Warszawa Lotnisko Chopina → Wieliszew": [
    {name: "Warszawa Lotnisko Chopina"},
    {name: "Warszawa Służewiec"},
    {name: "Warszawa Żwirki i Wigury"},
    {name: "Warszawa Rakowiec"},
    {name: "Warszawa Al.Jerozolimskie"},
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Centralna"},
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Praga"},
    {name: "Warszawa Toruńska"},
    {name: "Warszawa Żerań"},
    {name: "Warszawa Płudy"},
    {name: "Warszawa Choszczówka"},
    {name: "Legionowo"},
    {name: "Legionowo Piaski"},
    {name: "Michałów-Reginów"},
    {name: "Wieliszew"}
  ],

  "Wieliszew → Warszawa Lotnisko Chopina": [
    {name: "Wieliszew"},
    {name: "Michałów-Reginów"},
    {name: "Legionowo Piaski"},
    {name: "Legionowo"},
    {name: "Warszawa Choszczówka"},
    {name: "Warszawa Płudy"},
    {name: "Warszawa Żerań"},
    {name: "Warszawa Toruńska"},
    {name: "Warszawa Praga"},
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Centralna"},
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Al.Jerozolimskie"},
    {name: "Warszawa Rakowiec"},
    {name: "Warszawa Żwirki i Wigury"},
    {name: "Warszawa Służewiec"},
    {name: "Warszawa Lotnisko Chopina"}
  ],

  "Warszawa Zachodnia → Legionowo Piaski": [
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Kasprzaka"},
    {name: "Warszawa Koło"},
    {name: "Warszawa Gdańska"},
    {name: "Warszawa ZOO"},
    {name: "Warszawa Praga"},
    {name: "Warszawa Toruńska"},
    {name: "Warszawa Żerań"},
    {name: "Warszawa Płudy"},
    {name: "Warszawa Choszczówka"},
    {name: "Legionowo"},
    {name: "Legionowo Piaski"}
  ],

  "Legionowo Piaski → Warszawa Zachodnia": [
    {name: "Legionowo Piaski"},
    {name: "Legionowo"},
    {name: "Warszawa Choszczówka"},
    {name: "Warszawa Płudy"},
    {name: "Warszawa Żerań"},
    {name: "Warszawa Toruńska"},
    {name: "Warszawa Praga"},
    {name: "Warszawa ZOO"},
    {name: "Warszawa Gdańska"},
    {name: "Warszawa Koło"},
    {name: "Warszawa Kasprzaka"},
    {name: "Warszawa Zachodnia"}
  ],

  "Warszawa → Grodzisk Mazowiecki": [
    {name: "Warszawa Śródmieście WKD"},
    {name: "Warszawa Ochota WKD"},
    {name: "Warszawa Zachodnia WKD"},
    {name: "Warszawa Reduta Ordona"},
    {name: "Warszawa Aleje Jerozolimskie"},
    {name: "Warszawa Raków"},
    {name: "Warszawa Salomea"},
    {name: "Opacz"},
    {name: "Michałowice"},
    {name: "Reguły"},
    {name: "Malichy"},
    {name: "Tworki"},
    {name: "Pruszków WKD"},
    {name: "Komorów"},
    {name: "Nowa Wieś Warszawska"},
    {name: "Kanie Helenowskie"},
    {name: "Otrębusy"},
    {name: "Podkowa Leśna Wschodnia"},
    {name: "Podkowa Leśna Główna"},
    {name: "Podkowa Leśna Zachodnia"},
    {name: "Kazimierówka"},
    {name: "Brzózki"},
    {name: "Grodzisk Maz. Okrężna"},
    {name: "Grodzisk Maz. Piaskowa"},
    {name: "Grodzisk Maz. Jordanowice"},
    {name: "Grodzisk Maz. Radońska"},

  ],
  "Grodzisk Mazowiecki → Warszawa": [
    {name: "Grodzisk Maz. Radońska"},
    {name: "Grodzisk Maz. Jordanowice"},
    {name: "Grodzisk Maz. Piaskowa"},
    {name: "Grodzisk Maz. Okrężna"},
    {name: "Brzózki"},
    {name: "Kazimierówka"},
    {name: "Podkowa Leśna Zachodnia"},
    {name: "Podkowa Leśna Główna"},
    {name: "Podkowa Leśna Wschodnia"},
    {name: "Otrębusy"},
    {name: "Kanie Helenowskie"},
    {name: "Nowa Wieś Warszawska"},
    {name: "Komorów"},
    {name: "Pruszków WKD"},
    {name: "Tworki"},
    {name: "Malichy"},
    {name: "Reguły"},
    {name: "Michałowice"},
    {name: "Opacz"},
    {name: "Warszawa Salomea"},
    {name: "Warszawa Raków"},
    {name: "Warszawa Aleje Jerozolimskie"},
    {name: "Warszawa Reduta Ordona"},
    {name: "Warszawa Zachodnia WKD"},
    {name: "Warszawa Ochota WKD"},
    {name: "Warszawa Śródmieście WKD"},
  ],
  "Milanówek → Warszawa": [
    {name: "Milanówek Grudów"},
    {name: "Polesie"},
    {name: "Podkowa Leśna Zachodnia"},
    {name: "Podkowa Leśna Główna"},
    {name: "Podkowa Leśna Wschodnia"},
    {name: "Otrębusy"},
    {name: "Kanie Helenowskie"},
    {name: "Nowa Wieś Warszawska"},
    {name: "Komorów"},
    {name: "Pruszków WKD"},
    {name: "Tworki"},
    {name: "Malichy"},
    {name: "Reguły"},
    {name: "Michałowice"},
    {name: "Opacz"},
    {name: "Warszawa Salomea"},
    {name: "Warszawa Raków"},
    {name: "Warszawa Aleje Jerozolimskie"},
    {name: "Warszawa Reduta Ordona"},
    {name: "Warszawa Zachodnia WKD"},
    {name: "Warszawa Ochota WKD"},
    {name: "Warszawa Śródmieście WKD"},
  ],
  "Warszawa → Milanówek": [
    {name: "Warszawa Śródmieście WKD"},
    {name: "Warszawa Ochota WKD"},
    {name: "Warszawa Zachodnia WKD"},
    {name: "Warszawa Reduta Ordona"},
    {name: "Warszawa Aleje Jerozolimskie"},
    {name: "Warszawa Raków"},
    {name: "Warszawa Salomea"},
    {name: "Opacz"},
    {name: "Michałowice"},
    {name: "Reguły"},
    {name: "Malichy"},
    {name: "Tworki"},
    {name: "Pruszków WKD"},
    {name: "Komorów"},
    {name: "Nowa Wieś Warszawska"},
    {name: "Kanie Helenowskie"},
    {name: "Otrębusy"},
    {name: "Podkowa Leśna Wschodnia"},
    {name: "Podkowa Leśna Główna"},
    {name: "Podkowa Leśna Zachodnia"},
    {name: "Polesie"},
    {name: "Milanówek Grudów"},
  ],
  "Młociny → Kabaty": [
    {name: 'Młociny'},
    {name: 'Wawrzyszew'},
    {name: 'Stare Bielany'},
    {name: 'Słodowiec'},
    {name: 'Marymont'},
    {name: 'Plac Wilsona'},
    {name: 'Dworzec Gdański'},
    {name: 'Ratusz Arsenał'},
    {name: 'Świętokrzyska'},
    {name: 'Centrum'},
    {name: 'Politechnika'},
    {name: 'Pole Mokotowskie'},
    {name: 'Racławicka'},
    {name: 'Wierzbno'},
    {name: 'Wilanowska'},
    {name: 'Służew'},
    {name: 'Ursynów'},
    {name: 'Stokłosy'},
    {name: 'Imielin'},
    {name: 'Natolin'},
    {name: 'Kabaty'}
  ],
  "Kabaty → Młociny": [
    {name: 'Kabaty'},
    {name: 'Natolin'},
    {name: 'Imielin'},
    {name: 'Stokłosy'},
    {name: 'Ursynów'},
    {name: 'Służew'},
    {name: 'Wilanowska'},
    {name: 'Wierzbno'},
    {name: 'Racławicka'},
    {name: 'Pole Mokotowskie'},
    {name: 'Politechnika'},
    {name: 'Centrum'},
    {name: 'Świętokrzyska'},
    {name: 'Ratusz Arsenał'},
    {name: 'Dworzec Gdański'},
    {name: 'Plac Wilsona'},
    {name: 'Marymont'},
    {name: 'Słodowiec'},
    {name: 'Stare Bielany'},
    {name: 'Wawrzyszew'},
    {name: 'Młociny'}
  ],
  "Rondo Daszyńskiego → Dworzec Wileński": [
    {name: 'Rondo Daszyńskiego'},
    {name: 'Rondo ONZ'},
    {name: 'Świętokrzyska'},
    {name: 'Nowy Świat — Uniwersytet'},
    {name: 'Centrum Nauki Kopernik'},
    {name: 'Stadion Narodowy'},
    {name: 'Dworzec Wileński'}
  ],
  "Dworzec Wileński → Rondo Daszyńskiego": [
    {name: 'Dworzec Wileński'},
    {name: 'Stadion Narodowy'},
    {name: 'Centrum Nauki Kopernik'},
    {name: 'Nowy Świat — Uniwersytet'},
    {name: 'Świętokrzyska'},
    {name: 'Rondo ONZ'},
    {name: 'Rondo Daszyńskiego'}
  ],
};

