lines = {
  km: [
    {
      line: "KM1",
      color: "green-line",
      icon: "mdi-maps-directions-train",
      type: "km",
      directions: [
        {direction: "Warszawa Wschodnia → Pruszków"},
        {direction: "Pruszków → Warszawa Wschodnia"},
      ]
    },
    {
      line: "KM2",
      color: "green-line",
      icon: "mdi-maps-directions-train",
      type: "km",
      directions: [
        {direction: "Warszawa Zachodnia → Sulejówek Miłosna"},
        {direction: "Sulejówek Miłosna → Warszawa Zachodnia"},
      ]
    },
    {
      line: "KM3",
      color: "green-line",
      icon: "mdi-maps-directions-train",
      type: "km",
      directions: [
        {direction: "Warszawa Wschodnia → Płochocin"},
        {direction: "Płochocin → Warszawa Wschodnia"},
      ]
    },
    {
      line: "KM6",
      color: "green-line",
      icon: "mdi-maps-directions-train",
      type: "km",
      directions: [
        {direction: "Warszawa Zacisze Wilno → Warszawa Wileńska"},
        {direction: "Warszawa Wileńska → Warszawa Zacisze Wilno"},
      ]
    },
    {
      line: "KM7",
      color: "green-line",
      icon: "mdi-maps-directions-train",
      type: "km",
      directions: [
        {direction: "Warszawa Zachodnia → Śródborów"},
        {direction: "Śródborów → Warszawa Zachodnia"},
      ]
    },
    {
      line: "KM8",
      color: "green-line",
      icon: "mdi-maps-directions-train",
      type: "km",
      directions: [
        {direction: "Warszawa Wschodnia → Zalesie Górne"},
        {direction: "Zalesie Górne → Warszawa Wschodnia"},
      ]
    },
    {
      line: "KM9",
      color: "green-line",
      icon: "mdi-maps-directions-train",
      type: "km",
      directions: [
        {direction: "Warszawa Zachodnia → Legionowo Przystanek"},
        {direction: "Legionowo Przystanek → Warszawa Zachodnia"},
      ]
    },{
      line: "KML",
      color: "green-line",
      icon: "mdi-maps-directions-train",
      type: "km",
      directions: [
        {direction: "Warszawa Lotnisko Chopina → Legionowo Przystanek"},
        {direction: "Legionowo Przystanek → Warszawa Lotnisko Chopina"},
      ]
    },
  ],
  skm:[
    {
      line: "SKM S1",
      color: "orange-line",
      icon: "mdi-maps-directions-train",
      type: "skm",
      directions: [
        {direction: "Pruszków → Otwock"},
        {direction: "Otwock → Pruszków"},
      ]
    },
    {
      line: "SKM S2",
      color: "orange-line",
      icon: "mdi-maps-directions-train",
      type: "skm",
      directions: [
        {direction: "Warszawa Lotnisko Chopina → Sulejówek"},
        {direction: "Sulejówek → Warszawa Lotnisko Chopina"},
      ]
    },
    {
      line: "SKM S3",
      color: "orange-line",
      icon: "mdi-maps-directions-train",
      type: "skm",
      directions: [
        {direction: "Warszawa Lotnisko Chopina → Wieliszew"},
        {direction: "Wieliszew → Warszawa Lotnisko Chopina"},
      ]
    },
    {
      line: "SKM S9",
      color: "orange-line",
      icon: "mdi-maps-directions-train",
      type: "skm",
      directions: [
        {direction: "Warszawa Zachodnia → Legionowo Piaski"},
        {direction: "Legionowo Piaski → Warszawa Zachodnia"},
      ]
    },
    
    
    
  ],
  wkd: [
    {
      line: "WKD",
      color: "purple-line",
      icon: "mdi-maps-directions-train",
      type: "wkd",
      directions: [
        {direction: "Grodzisk Mazowiecki → Warszawa"},
        {direction: "Warszawa → Grodzisk Mazowiecki"},
        {direction: "Milanówek → Warszawa"},
        {direction: "Warszawa → Milanówek"}
      ]
    },
  ],
  metro: [
    {
      line: "Metro M1",
      color: "blue-line",
      icon: "mdi-maps-directions-subway",
      type: "metro",
      directions: [
        {direction: "→ Kabaty"},
        {direction: "→ Młociny"}
      ]
    },
    {
      line: "Metro M2",
      color: "red-line",
      icon: "mdi-maps-directions-subway",
      type: "metro",
      directions: [
        {direction: "→ Dworzec Wileński"},
        {direction: "→ Rondo Daszyńskiego"}
      ]
    },
  ]
};

stations = {
  "Warszawa Lotnisko Chopina → Legionowo Przystanek":[],
  "Legionowo Przystanek → Warszawa Lotnisko Chopina":[],
  "Warszawa Zachodnia → Legionowo Przystanek":[],
  "Legionowo Przystanek → Warszawa Zachodnia":[],
  "Warszawa Wschodnia → Zalesie Górne":[],
  "Zalesie Górne → Warszawa Wschodnia":[],
  "Warszawa Zachodnia → Śródborów":[],
  "Śródborów → Warszawa Zachodnia":[],
  "Warszawa Zacisze Wilno → Warszawa Wileńska":[],
  "Warszawa Wileńska → Warszawa Zacisze Wilno":[],
  "Warszawa Wschodnia → Płochocin":[],
  "Płochocin → Warszawa Wschodnia":[],
  "Warszawa Zachodnia → Sulejówek Miłosna": [
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Ochota"},
    {name: "Warszawa Śródmieście"},
    {name: "Warszawa Powiśle"},
    {name: "Warszawa Stadion"},
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Rembertów"},
    {name: "Warszawa Wesoła"},
    {name: "Warszawa Wola Grzybowska"},
    {name: "Sulejówek"},
    {name: "Sulejówek Miłosna"}
  ],
  "Sulejówek Miłosna → Warszawa Zachodnia": [
    {name: "Sulejówek Miłosna"},
    {name: "Sulejówek"},
    {name: "Warszawa Wola Grzybowska"},
    {name: "Warszawa Wesoła"},
    {name: "Warszawa Rembertów"},
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Stadion"},
    {name: "Warszawa Powiśle"},
    {name: "Warszawa Śródmieście"},
    {name: "Warszawa Ochota"},
    {name: "Warszawa Zachodnia"}
  ],
  "Warszawa Wschodnia → Pruszków": [
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Stadion"},
    {name: "Warszawa Powiśle"},
    {name: "Warszawa Śródmieście"},
    {name: "Warszawa Ochota"},
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Włochy"},
    {name: "Warszawa Ursus"},
    {name: "Warszawa Ursus-Niedźwiadek"},
    {name: "Piastów"},
    {name: "Pruszków"},
  ],
  "Pruszków → Warszawa Wschodnia":[
    {name: "Pruszków"},
    {name: "Piastów"},
    {name: "Warszawa Ursus-Niedźwiadek"},
    {name: "Warszawa Ursus"},
    {name: "Warszawa Włochy"},
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Ochota"},
    {name: "Warszawa Śródmieście"},
    {name: "Warszawa Powiśle"},
    {name: "Warszawa Stadion"},
    {name: "Warszawa Wschodnia"},
  ],
  "Pruszków → Otwock": [
    {name: "Pruszków"},
    {name: "Piastów"},
    {name: "Warszawa Ursus-Niedźwiadek"},
    {name: "Warszawa Ursus"},
    {name: "Warszawa Włochy"},
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Ochota"},
    {name: "Warszawa Śródmieście"},
    {name: "Warszawa Powiśle"},
    {name: "Warszawa Stadion"},
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Olszynka Grochowska"},
    {name: "Warszawa Gocławek"},
    {name: "Warszawa Wawer"},
    {name: "Warszawa Anin"},
    {name: "Warszawa Międzylesie"},
    {name: "Warszawa Radość"},
    {name: "Warszawa Miedzeszyn"},
    {name: "Warszawa Falenica"},
    {name: "Michalin"},
    {name: "Józefów"},
    {name: "Świder"},
    {name: "Otwock"}
  ],

  "Otwock → Pruszków": [
    {name: "Otwock"},
    {name: "Świder"},
    {name: "Józefów"},
    {name: "Michalin"},
    {name: "Warszawa Falenica"},
    {name: "Warszawa Miedzeszyn"},
    {name: "Warszawa Radość"},
    {name: "Warszawa Międzylesie"},
    {name: "Warszawa Anin"},
    {name: "Warszawa Wawer"},
    {name: "Warszawa Gocławek"},
    {name: "Warszawa Olszynka Grochowska"},
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Stadion"},
    {name: "Warszawa Powiśle"},
    {name: "Warszawa Śródmieście"},
    {name: "Warszawa Ochota"},
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Włochy"},
    {name: "Warszawa Ursus"},
    {name: "Warszawa Ursus-Niedźwiadek"},
    {name: "Piastów"},
    {name: "Pruszków"},
  ],

  "Warszawa Lotnisko Chopina → Sulejówek": [
    {name: "Warszawa Lotnisko Chopina"},
    {name: "Warszawa Służewiec"},
    {name: "Warszawa Żwirki I Wigury"},
    {name: "Warszawa Rakowiec"},
    {name: "Warszawa Al.Jerozolimskie"},
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Ochota"},
    {name: "Warszawa Śródmieście"},
    {name: "Warszawa Powiśle"},
    {name: "Warszawa Stadion"},
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Rembertów"},
    {name: "Warszawa Wesoła"},
    {name: "Warszawa Wola Grzybowska"},
    {name: "Sulejówek"},
    {name: "Sulejówek Miłosna"}
  ],

  "Sulejówek → Warszawa Lotnisko Chopina": [
    {name: "Sulejówek Miłosna"},
    {name: "Sulejówek"},
    {name: "Warszawa Wola Grzybowska"},
    {name: "Warszawa Wesoła"},
    {name: "Warszawa Rembertów"},
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Stadion"},
    {name: "Warszawa Powiśle"},
    {name: "Warszawa Śródmieście"},
    {name: "Warszawa Ochota"},
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Al.Jerozolimskie"},
    {name: "Warszawa Rakowiec"},
    {name: "Warszawa Żwirki I Wigury"},
    {name: "Warszawa Służewiec"},
    {name: "Warszawa Lotnisko Chopina"}
  ],

  "Warszawa Lotnisko Chopina → Wieliszew": [
    {name: "Warszawa Lotnisko Chopina"},
    {name: "Warszawa Służewiec"},
    {name: "Warszawa Żwirki i Wigury"},
    {name: "Warszawa Rakowiec"},
    {name: "Warszawa Al.Jerozolimskie"},
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Centralna"},
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Praga"},
    {name: "Warszawa Toruńska"},
    {name: "Warszawa Żerań"},
    {name: "Warszawa Płudy"},
    {name: "Warszawa Choszczówka"},
    {name: "Legionowo"},
    {name: "Legionowo Piaski"},
    {name: "Michałów-Reginów"},
    {name: "Wieliszew"}
  ],

  "Wieliszew → Warszawa Lotnisko Chopina": [
    {name: "Wieliszew"},
    {name: "Michałów-Reginów"},
    {name: "Legionowo Piaski"},
    {name: "Legionowo"},
    {name: "Warszawa Choszczówka"},
    {name: "Warszawa Płudy"},
    {name: "Warszawa Żerań"},
    {name: "Warszawa Toruńska"},
    {name: "Warszawa Praga"},
    {name: "Warszawa Wschodnia"},
    {name: "Warszawa Centralna"},
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Al.Jerozolimskie"},
    {name: "Warszawa Rakowiec"},
    {name: "Warszawa Żwirki i Wigury"},
    {name: "Warszawa Służewiec"},
    {name: "Warszawa Lotnisko Chopina"}
  ],

  "Warszawa Zachodnia → Legionowo Piaski": [
    {name: "Warszawa Zachodnia"},
    {name: "Warszawa Kasprzaka"},
    {name: "Warszawa Koło"},
    {name: "Warszawa Gdańska"},
    {name: "Warszawa ZOO"},
    {name: "Warszawa Praga"},
    {name: "Warszawa Toruńska"},
    {name: "Warszawa Żerań"},
    {name: "Warszawa Płudy"},
    {name: "Warszawa Choszczówka"},
    {name: "Legionowo"},
    {name: "Legionowo Piaski"}
  ],

  "Legionowo Piaski → Warszawa Zachodnia": [
    {name: "Legionowo Piaski"},
    {name: "Legionowo"},
    {name: "Warszawa Choszczówka"},
    {name: "Warszawa Płudy"},
    {name: "Warszawa Żerań"},
    {name: "Warszawa Toruńska"},
    {name: "Warszawa Praga"},
    {name: "Warszawa ZOO"},
    {name: "Warszawa Gdańska"},
    {name: "Warszawa Koło"},
    {name: "Warszawa Kasprzaka"},
    {name: "Warszawa Zachodnia"}
  ],

  "Warszawa → Grodzisk Mazowiecki": [
    {name: "Warszawa Śródmieście WKD"},
    {name: "Warszawa Ochota WKD"},
    {name: "Warszawa Zachodnia WKD"},
    {name: "Warszawa Reduta Ordona"},
    {name: "Warszawa Aleje Jerozolimskie"},
    {name: "Warszawa Raków"},
    {name: "Warszawa Salomea"},
    {name: "Opacz"},
    {name: "Michałowice"},
    {name: "Reguły"},
    {name: "Malichy"},
    {name: "Tworki"},
    {name: "Pruszków WKD"},
    {name: "Komorów"},
    {name: "Nowa Wieś Warszawska"},
    {name: "Kanie Helenowskie"},
    {name: "Otrębusy"},
    {name: "Podkowa Leśna Wschodnia"},
    {name: "Podkowa Leśna Główna"},
    {name: "Podkowa Leśna Zachodnia"},
    {name: "Kazimierówka"},
    {name: "Brzózki"},
    {name: "Grodzisk Maz. Okrężna"},
    {name: "Grodzisk Maz. Piaskowa"},
    {name: "Grodzisk Maz. Jordanowice"},
    {name: "Grodzisk Maz. Radońska"},

  ],
  "Grodzisk Mazowiecki → Warszawa": [
    {name: "Grodzisk Maz. Radońska"},
    {name: "Grodzisk Maz. Jordanowice"},
    {name: "Grodzisk Maz. Piaskowa"},
    {name: "Grodzisk Maz. Okrężna"},
    {name: "Brzózki"},
    {name: "Kazimierówka"},
    {name: "Podkowa Leśna Zachodnia"},
    {name: "Podkowa Leśna Główna"},
    {name: "Podkowa Leśna Wschodnia"},
    {name: "Otrębusy"},
    {name: "Kanie Helenowskie"},
    {name: "Nowa Wieś Warszawska"},
    {name: "Komorów"},
    {name: "Pruszków WKD"},
    {name: "Tworki"},
    {name: "Malichy"},
    {name: "Reguły"},
    {name: "Michałowice"},
    {name: "Opacz"},
    {name: "Warszawa Salomea"},
    {name: "Warszawa Raków"},
    {name: "Warszawa Aleje Jerozolimskie"},
    {name: "Warszawa Reduta Ordona"},
    {name: "Warszawa Zachodnia WKD"},
    {name: "Warszawa Ochota WKD"},
    {name: "Warszawa Śródmieście WKD"},
  ],
  "Milanówek → Warszawa": [
    {name: "Milanówek Grudów"},
    {name: "Polesie"},
    {name: "Podkowa Leśna Zachodnia"},
    {name: "Podkowa Leśna Główna"},
    {name: "Podkowa Leśna Wschodnia"},
    {name: "Otrębusy"},
    {name: "Kanie Helenowskie"},
    {name: "Nowa Wieś Warszawska"},
    {name: "Komorów"},
    {name: "Pruszków WKD"},
    {name: "Tworki"},
    {name: "Malichy"},
    {name: "Reguły"},
    {name: "Michałowice"},
    {name: "Opacz"},
    {name: "Warszawa Salomea"},
    {name: "Warszawa Raków"},
    {name: "Warszawa Aleje Jerozolimskie"},
    {name: "Warszawa Reduta Ordona"},
    {name: "Warszawa Zachodnia WKD"},
    {name: "Warszawa Ochota WKD"},
    {name: "Warszawa Śródmieście WKD"},
  ],
  "Warszawa → Milanówek": [
    {name: "Warszawa Śródmieście WKD"},
    {name: "Warszawa Ochota WKD"},
    {name: "Warszawa Zachodnia WKD"},
    {name: "Warszawa Reduta Ordona"},
    {name: "Warszawa Aleje Jerozolimskie"},
    {name: "Warszawa Raków"},
    {name: "Warszawa Salomea"},
    {name: "Opacz"},
    {name: "Michałowice"},
    {name: "Reguły"},
    {name: "Malichy"},
    {name: "Tworki"},
    {name: "Pruszków WKD"},
    {name: "Komorów"},
    {name: "Nowa Wieś Warszawska"},
    {name: "Kanie Helenowskie"},
    {name: "Otrębusy"},
    {name: "Podkowa Leśna Wschodnia"},
    {name: "Podkowa Leśna Główna"},
    {name: "Podkowa Leśna Zachodnia"},
    {name: "Polesie"},
    {name: "Milanówek Grudów"},
  ],
  "→ Kabaty": [
    {name: 'Młociny'},
    {name: 'Wawrzyszew'},
    {name: 'Stare Bielany'},
    {name: 'Słodowiec'},
    {name: 'Marymont'},
    {name: 'Plac Wilsona'},
    {name: 'Dworzec Gdański'},
    {name: 'Ratusz Arsenał'},
    {name: 'Świętokrzyska'},
    {name: 'Centrum'},
    {name: 'Politechnika'},
    {name: 'Pole Mokotowskie'},
    {name: 'Racławicka'},
    {name: 'Wierzbno'},
    {name: 'Wilanowska'},
    {name: 'Służew'},
    {name: 'Ursynów'},
    {name: 'Stokłosy'},
    {name: 'Imielin'},
    {name: 'Natolin'},
    {name: 'Kabaty'}
  ],
  "→ Młociny": [
    {name: 'Kabaty'},
    {name: 'Natolin'},
    {name: 'Imielin'},
    {name: 'Stokłosy'},
    {name: 'Ursynów'},
    {name: 'Służew'},
    {name: 'Wilanowska'},
    {name: 'Wierzbno'},
    {name: 'Racławicka'},
    {name: 'Pole Mokotowskie'},
    {name: 'Politechnika'},
    {name: 'Centrum'},
    {name: 'Świętokrzyska'},
    {name: 'Ratusz Arsenał'},
    {name: 'Dworzec Gdański'},
    {name: 'Plac Wilsona'},
    {name: 'Marymont'},
    {name: 'Słodowiec'},
    {name: 'Stare Bielany'},
    {name: 'Wawrzyszew'},
    {name: 'Młociny'}
  ],
  "→ Dworzec Wileński": [
    {name: 'Rondo Daszyńskiego'},
    {name: 'Rondo ONZ'},
    {name: 'Świętokrzyska'},
    {name: 'Nowy Świat — Uniwersytet'},
    {name: 'Centrum Nauki Kopernik'},
    {name: 'Stadion Narodowy'},
    {name: 'Dworzec Wileński'}
  ],
  "→ Rondo Daszyńskiego": [
    {name: 'Dworzec Wileński'},
    {name: 'Stadion Narodowy'},
    {name: 'Centrum Nauki Kopernik'},
    {name: 'Nowy Świat — Uniwersytet'},
    {name: 'Świętokrzyska'},
    {name: 'Rondo ONZ'},
    {name: 'Rondo Daszyńskiego'}
  ],
};

